// Pool "Top 150" (los mejores jugadores actuales). Lo usa el sobre diario para
// la 2a carta garantizada. Curado por id: cada nombre+pais se verifico contra
// el dataset (generated/data.ts). Los del top-150 que NO estan en las
// plantillas del Mundial quedan fuera, asi que el pool son los que SI estan.
export const TOP150_PLAYER_IDS = [
  "esp-19", // Lamine Yamal (Lamine Yamal)
  "nor-09", // Erling Haaland (Braut Haaland)
  "fra-10", // Kylian Mbappé (Mbappe)
  "esp-20", // Pedri (Pedri)
  "fra-11", // Michael Olise (Olise)
  "por-23", // Vitinha (Vitinha)
  "por-15", // João Neves (João Neves)
  "bra-07", // Vinicius Junior (Vini Jr.)
  "eng-10", // Jude Bellingham (Bellingham)
  "eng-04", // Declan Rice (Rice)
  "fra-20", // Désiré Doué (Doue)
  "eng-07", // Bukayo Saka (Saka)
  "ger-10", // Jamal Musiala (Musiala)
  "ger-17", // Florian Wirtz (Wirtz)
  "ecu-23", // Moisés Caicedo (M. Caicedo)
  "arg-09", // Julián Alvarez (J. Alvarez)
  "fra-07", // Ousmane Dembélé (Dembele)
  "fra-17", // William Saliba (Saliba)
  "ger-05", // Aleksandar Pavlovic (Pavlovic)
  "eng-17", // Morgan Rogers (Rogers)
  "uru-08", // Federico Valverde (F. Valverde)
  "tur-08", // Arda Güler (Arda Güler)
  "arg-24", // Enzo Fernández (E. Fernández)
  "civ-11", // Yan Diomande (Yan Diomande)
  "fra-24", // Rayan Cherki (Cherki)
  "swe-09", // Alexander Isak (Isak)
  "arg-22", // Lautaro Martínez (L. Martínez)
  "mar-02", // Achraf Hakimi (Hakimi)
  "ecu-06", // Willian Pacho (Pacho)
  "gha-11", // Antoine Semenyo (Semenyo)
  "por-25", // Nuno Mendes (N. Mendes)
  "arg-18", // Nico Paz (Nico Paz)
  "esp-22", // Pau Cubarsí (Cubarsi)
  "fra-18", // Warren Zaïre-Emery (Zaire Emery)
  "ned-08", // Ryan Gravenberch (Gravenberch)
  "eng-08", // Elliot Anderson (Anderson)
  "bel-11", // Jérémy Doku (Doku)
  "tur-11", // Kenan Yıldız (Yildiz)
  "esp-18", // Martín Zubimendi (Zubimendi)
  "bra-03", // Gabriel (Gabriel)
  "bra-09", // Matheus Cunha (Cunha)
  "col-07", // Luis Díaz (Luis Diaz)
  "eng-06", // Marc Guéhi (Guehi)
  "eng-03", // Nico O’Reilly (O'Reilly)
  "eng-16", // Kobbie Mainoo (Mainoo)
  "arg-20", // Alexis Mac Allister (Mac Allister)
  "bra-11", // Raphinha (Raphinha)
  "fra-04", // Dayot Upamecano (Upamecano)
  "fra-08", // Aurélien Tchouaméni (Tchouameni)
  "fra-12", // Bradley Barcola (Barcola)
  "bra-08", // Bruno Guimarães (Bruno G.)
  "cro-04", // Joško Gvardiol (Gvardiol)
  "eng-21", // Eberechi Eze (Eze)
  "eng-18", // Anthony Gordon (Gordon)
  "swe-17", // Viktor Gyökeres (Gyökeres)
  "bra-25", // Igor Thiago (Thiago)
  "nor-10", // Martin Ødegaard (Ødegaard)
  "eng-09", // Harry Kane (Kane)
  "eng-24", // Reece James (James)
  "cro-22", // Luka Vušković (Vuskovic)
  "por-18", // Pedro Neto (Neto)
  "esp-10", // Dani Olmo (Olmo)
  "fra-05", // Jules Koundé (Kounde)
  "bra-26", // Rayan (Rayan)
  "ned-11", // Cody Gakpo (Gakpo)
  "ger-07", // Kai Havertz (Havertz)
  "ger-15", // Nico Schlotterbeck (Schlotterbeck)
  "ger-11", // Nick Woltemade (Woltemade)
  "sen-13", // Iliman Ndiaye (Ndiaye)
  "por-03", // Rúben Dias (Rúben Dias)
  "uzb-02", // Abdukodir Khusanov (Khusanov)
  "sui-09", // Johan Manzambi (Manzambi)
  "ger-23", // Felix Nmecha (Nmecha)
  "ecu-03", // Piero Hincapié (Hincapie)
  "mar-06", // Ayyoub Bouaddi (Bouaddi)
  "egy-22", // Omar Marmoush (Marmoush)
  "por-06", // Matheus Nunes (Matheus N.)
  "por-17", // Rafael Leão (Rafa Leão)
  "fra-25", // Maghnes Akliouche (Akliouche)
  "fra-06", // Manu Koné (Kone)
  "fra-26", // Maxence Lacroix (Lacroix)
  "fra-09", // Marcus Thuram (Thuram)
  "esp-07", // Ferran Torres (Ferran)
  "esp-16", // Rodri (Rodrigo)
  "esp-24", // Marc Cucurella (Cucurella)
  "eng-20", // Noni Madueke (Madueke)
  "bra-22", // Gabriel Martinelli (Martinelli)
  "bra-23", // Éderson (Ederson)
  "bel-24", // Amadou Onana (Onana)
  "ned-06", // Jan Paul van Hecke (Van Hecke)
  "ned-18", // Donyell Malen (Malen)
  "ger-24", // Malick Thiaw (Thiaw)
  "ger-16", // Angelo Stiller (Stiller)
  "alg-22", // Ibrahim Maza (Maza)
  "esp-13", // Joan García (Joan García)
  "fra-15", // Ibrahima Konaté (Konate)
  "civ-15", // Amad Diallo (Amad)
  "arg-13", // Cristian Romero (Romero)
  "civ-02", // Ousmane Diomande (O. Diomande)
  "sui-01", // Gregor Kobel (Kobel)
  "sen-18", // Ismaïla Sarr (Sarr)
  "usa-20", // Folarin Balogun (Balogun)
  "sen-26", // Pape Gueye (Gueye)
  "mar-11", // Ismael Saibari (Saibari)
  "ger-09", // Jamie Leweling (Leweling)
  "ger-14", // Maximilian Beier (Beier)
  "ger-18", // Nathaniel Brown (Brown)
  "alg-15", // Rayan Aït-Nouri (Ait Nouri)
  "sen-11", // Nicolas Jackson (Jackson)
  "can-19", // Alphonso Davies (Davies)
  "eng-11", // Marcus Rashford (Rashford)
  "eng-02", // Ezri Konsa (Konsa)
  "jpn-24", // Kaishu Sano (Sano)
  "por-01", // Diogo Costa (Diogo Costa)
  "por-16", // Francisco Trincão (Trincão)
  "por-14", // Gonçalo Inácio (G. Inácio)
  "usa-10", // Christian Pulisic (Pulisic)
  "cro-17", // Petar Sučić (P. Sucic)
  "arg-06", // Lisandro Martínez (Martínez)
  "esp-15", // Álex Baena (Alex B.)
  "arg-17", // Giuliano Simeone (Simeone)
  "arg-08", // Valentín Barco (Barco)
  "esp-17", // Nico Williams (Williams Jr)
  "cro-02", // Josip Stanišić (Stanisic)
  "sen-08", // Lamine Camara (Lamine)
  "nor-11", // Jørgen Strand Larsen (Strand Larsen)
  "sco-04", // Scott McTominay (Mctominay)
  "civ-24", // Bazoumana Touré (Toure)
  "bra-19", // Endrick (Endrick)
  "ned-25", // Jorrel Hato (Hato)
  "ned-01", // Bart Verbruggen (Verbruggen)
  "civ-09", // Ange-Yoan Bonny (Bonny)
  "mar-10", // Brahim Díaz (Brahim)
  "mar-23", // Bilal El Khannouss (El Khannouss)
  "cod-14", // Noah Sadiki (Sadiki)
  "swe-07", // Lucas Bergvall (Bergvall)
  "swe-18", // Yasin Ayari (Ayari)
  "bel-26", // Matias Fernandez-Pardo (Fernandez-Pardo)
  "bel-12", // Senne Lammens (Lammens)
  "sen-21", // Habib Diarra (H. Diarra)
  "uru-20", // Maxi Araújo (M. Araujo)
  "tur-20", // Ferdi Kadıoğlu (F. Kadioğlu)
  "bra-14", // Bremer (Bremer)
  "civ-21", // Evan Ndicka (Ndicka)
  "ger-06", // Joshua Kimmich (Kimmich)
  "ned-21", // Frenkie de Jong (F. De Jong)
];
