-- Run after schema.sql. The groups reflect FIFA's published World Cup 2026 draw.
insert into public.teams (id, fifa_code, name, flag_code, group_code) values
  ('mex', 'MEX', 'México', 'mx', 'A'),
  ('kor', 'KOR', 'Corea del Sur', 'kr', 'A'),
  ('rsa', 'RSA', 'Sudáfrica', 'za', 'A'),
  ('cze', 'CZE', 'Chequia', 'cz', 'A'),
  ('can', 'CAN', 'Canadá', 'ca', 'B'),
  ('qat', 'QAT', 'Catar', 'qa', 'B'),
  ('sui', 'SUI', 'Suiza', 'ch', 'B'),
  ('bih', 'BIH', 'Bosnia y Herzegovina', 'ba', 'B'),
  ('bra', 'BRA', 'Brasil', 'br', 'C'),
  ('mar', 'MAR', 'Marruecos', 'ma', 'C'),
  ('hai', 'HAI', 'Haití', 'ht', 'C'),
  ('sco', 'SCO', 'Escocia', 'gb-sct', 'C'),
  ('usa', 'USA', 'Estados Unidos', 'us', 'D'),
  ('aus', 'AUS', 'Australia', 'au', 'D'),
  ('par', 'PAR', 'Paraguay', 'py', 'D'),
  ('tur', 'TUR', 'Türkiye', 'tr', 'D'),
  ('ger', 'GER', 'Alemania', 'de', 'E'),
  ('civ', 'CIV', 'Costa de Marfil', 'ci', 'E'),
  ('ecu', 'ECU', 'Ecuador', 'ec', 'E'),
  ('cuw', 'CUW', 'Curazao', 'cw', 'E'),
  ('ned', 'NED', 'Países Bajos', 'nl', 'F'),
  ('jpn', 'JPN', 'Japón', 'jp', 'F'),
  ('swe', 'SWE', 'Suecia', 'se', 'F'),
  ('tun', 'TUN', 'Túnez', 'tn', 'F'),
  ('bel', 'BEL', 'Bélgica', 'be', 'G'),
  ('egy', 'EGY', 'Egipto', 'eg', 'G'),
  ('irn', 'IRN', 'Irán', 'ir', 'G'),
  ('nzl', 'NZL', 'Nueva Zelanda', 'nz', 'G'),
  ('esp', 'ESP', 'España', 'es', 'H'),
  ('cpv', 'CPV', 'Cabo Verde', 'cv', 'H'),
  ('ksa', 'KSA', 'Arabia Saudí', 'sa', 'H'),
  ('uru', 'URU', 'Uruguay', 'uy', 'H'),
  ('fra', 'FRA', 'Francia', 'fr', 'I'),
  ('sen', 'SEN', 'Senegal', 'sn', 'I'),
  ('irq', 'IRQ', 'Irak', 'iq', 'I'),
  ('nor', 'NOR', 'Noruega', 'no', 'I'),
  ('arg', 'ARG', 'Argentina', 'ar', 'J'),
  ('alg', 'ALG', 'Argelia', 'dz', 'J'),
  ('aut', 'AUT', 'Austria', 'at', 'J'),
  ('jor', 'JOR', 'Jordania', 'jo', 'J'),
  ('por', 'POR', 'Portugal', 'pt', 'K'),
  ('cod', 'COD', 'RD del Congo', 'cd', 'K'),
  ('uzb', 'UZB', 'Uzbekistán', 'uz', 'K'),
  ('col', 'COL', 'Colombia', 'co', 'K'),
  ('eng', 'ENG', 'Inglaterra', 'gb-eng', 'L'),
  ('cro', 'CRO', 'Croacia', 'hr', 'L'),
  ('gha', 'GHA', 'Ghana', 'gh', 'L'),
  ('pan', 'PAN', 'Panamá', 'pa', 'L')
on conflict (id) do update set
  fifa_code = excluded.fifa_code,
  name = excluded.name,
  flag_code = excluded.flag_code,
  group_code = excluded.group_code;

-- Demo player catalog used by the MVP UI. Replace with validated FIFA squads before opening publicly.
insert into public.players (id, team_id, display_name, position, squad_status) values
  ('martinez', 'arg', 'Emiliano Martínez', 'POR', 'provisional'),
  ('alisson', 'bra', 'Alisson Becker', 'POR', 'provisional'),
  ('simon', 'esp', 'Unai Simón', 'POR', 'provisional'),
  ('maignan', 'fra', 'Mike Maignan', 'POR', 'provisional'),
  ('bounou', 'mar', 'Yassine Bounou', 'POR', 'provisional'),
  ('dibu', 'uru', 'Sergio Rochet', 'POR', 'provisional'),
  ('gvardiol', 'cro', 'Joško Gvardiol', 'DEF', 'provisional'),
  ('saliba', 'fra', 'William Saliba', 'DEF', 'provisional'),
  ('hakimi', 'mar', 'Achraf Hakimi', 'DEF', 'provisional'),
  ('dias', 'por', 'Rúben Dias', 'DEF', 'provisional'),
  ('romero', 'arg', 'Cristian Romero', 'DEF', 'provisional'),
  ('van-dijk', 'ned', 'Virgil van Dijk', 'DEF', 'provisional'),
  ('trent', 'eng', 'Trent Alexander-Arnold', 'DEF', 'provisional'),
  ('theo', 'fra', 'Theo Hernández', 'DEF', 'provisional'),
  ('davies', 'can', 'Alphonso Davies', 'DEF', 'provisional'),
  ('araujo', 'uru', 'Ronald Araújo', 'DEF', 'provisional'),
  ('rodri', 'esp', 'Rodri', 'MED', 'provisional'),
  ('bellingham', 'eng', 'Jude Bellingham', 'MED', 'provisional'),
  ('valverde', 'uru', 'Federico Valverde', 'MED', 'provisional'),
  ('pedri', 'esp', 'Pedri', 'MED', 'provisional'),
  ('vitinha', 'por', 'Vitinha', 'MED', 'provisional'),
  ('wirtz', 'ger', 'Florian Wirtz', 'MED', 'provisional'),
  ('mac-allister', 'arg', 'Alexis Mac Allister', 'MED', 'provisional'),
  ('hakha', 'tur', 'Hakan Çalhanoğlu', 'MED', 'provisional'),
  ('kdb', 'bel', 'Kevin De Bruyne', 'MED', 'provisional'),
  ('odegaard', 'nor', 'Martin Ødegaard', 'MED', 'provisional'),
  ('kudus', 'gha', 'Mohammed Kudus', 'MED', 'provisional'),
  ('enzo', 'arg', 'Enzo Fernández', 'MED', 'provisional'),
  ('yamal', 'esp', 'Lamine Yamal', 'DEL', 'provisional'),
  ('mbappe', 'fra', 'Kylian Mbappé', 'DEL', 'provisional'),
  ('vinicius', 'bra', 'Vinícius Júnior', 'DEL', 'provisional'),
  ('haaland', 'nor', 'Erling Haaland', 'DEL', 'provisional'),
  ('kane', 'eng', 'Harry Kane', 'DEL', 'provisional'),
  ('lautaro', 'arg', 'Lautaro Martínez', 'DEL', 'provisional'),
  ('salah', 'egy', 'Mohamed Salah', 'DEL', 'provisional'),
  ('leao', 'por', 'Rafael Leão', 'DEL', 'provisional'),
  ('diaz', 'col', 'Luis Díaz', 'DEL', 'provisional'),
  ('pulisic', 'usa', 'Christian Pulisic', 'DEL', 'provisional'),
  ('kubo', 'jpn', 'Takefusa Kubo', 'DEL', 'provisional'),
  ('mane', 'sen', 'Sadio Mané', 'DEL', 'provisional')
on conflict (id) do update set
  team_id = excluded.team_id,
  display_name = excluded.display_name,
  position = excluded.position,
  squad_status = excluded.squad_status;
