window.PORRA_DATA = {
  tournament: {
    name: "Mundial 2026",
    startsAt: "2026-06-11",
    endsAt: "2026-07-19",
    lockAt: "2026-06-11T19:00:00Z",
  },
  teams: [
    { id: "mex", name: "México", code: "mx", group: "A" },
    { id: "kor", name: "Corea del Sur", code: "kr", group: "A" },
    { id: "rsa", name: "Sudáfrica", code: "za", group: "A" },
    { id: "cze", name: "Chequia", code: "cz", group: "A" },
    { id: "can", name: "Canadá", code: "ca", group: "B" },
    { id: "qat", name: "Catar", code: "qa", group: "B" },
    { id: "sui", name: "Suiza", code: "ch", group: "B" },
    { id: "bih", name: "Bosnia y Herzegovina", code: "ba", group: "B" },
    { id: "bra", name: "Brasil", code: "br", group: "C" },
    { id: "mar", name: "Marruecos", code: "ma", group: "C" },
    { id: "hai", name: "Haití", code: "ht", group: "C" },
    { id: "sco", name: "Escocia", code: "gb-sct", group: "C" },
    { id: "usa", name: "Estados Unidos", code: "us", group: "D" },
    { id: "aus", name: "Australia", code: "au", group: "D" },
    { id: "par", name: "Paraguay", code: "py", group: "D" },
    { id: "tur", name: "Türkiye", code: "tr", group: "D" },
    { id: "ger", name: "Alemania", code: "de", group: "E" },
    { id: "civ", name: "Costa de Marfil", code: "ci", group: "E" },
    { id: "ecu", name: "Ecuador", code: "ec", group: "E" },
    { id: "cuw", name: "Curazao", code: "cw", group: "E" },
    { id: "ned", name: "Países Bajos", code: "nl", group: "F" },
    { id: "jpn", name: "Japón", code: "jp", group: "F" },
    { id: "swe", name: "Suecia", code: "se", group: "F" },
    { id: "tun", name: "Túnez", code: "tn", group: "F" },
    { id: "bel", name: "Bélgica", code: "be", group: "G" },
    { id: "egy", name: "Egipto", code: "eg", group: "G" },
    { id: "irn", name: "Irán", code: "ir", group: "G" },
    { id: "nzl", name: "Nueva Zelanda", code: "nz", group: "G" },
    { id: "esp", name: "España", code: "es", group: "H" },
    { id: "cpv", name: "Cabo Verde", code: "cv", group: "H" },
    { id: "ksa", name: "Arabia Saudí", code: "sa", group: "H" },
    { id: "uru", name: "Uruguay", code: "uy", group: "H" },
    { id: "fra", name: "Francia", code: "fr", group: "I" },
    { id: "sen", name: "Senegal", code: "sn", group: "I" },
    { id: "irq", name: "Irak", code: "iq", group: "I" },
    { id: "nor", name: "Noruega", code: "no", group: "I" },
    { id: "arg", name: "Argentina", code: "ar", group: "J" },
    { id: "alg", name: "Argelia", code: "dz", group: "J" },
    { id: "aut", name: "Austria", code: "at", group: "J" },
    { id: "jor", name: "Jordania", code: "jo", group: "J" },
    { id: "por", name: "Portugal", code: "pt", group: "K" },
    { id: "cod", name: "RD del Congo", code: "cd", group: "K" },
    { id: "uzb", name: "Uzbekistán", code: "uz", group: "K" },
    { id: "col", name: "Colombia", code: "co", group: "K" },
    { id: "eng", name: "Inglaterra", code: "gb-eng", group: "L" },
    { id: "cro", name: "Croacia", code: "hr", group: "L" },
    { id: "gha", name: "Ghana", code: "gh", group: "L" },
    { id: "pan", name: "Panamá", code: "pa", group: "L" },
  ],
  // Demo catalog. Replace it with the validated FIFA squad import before opening predictions.
  players: [
    { id: "martinez", name: "Emiliano Martínez", team: "arg", position: "POR" },
    { id: "alisson", name: "Alisson Becker", team: "bra", position: "POR" },
    { id: "simon", name: "Unai Simón", team: "esp", position: "POR" },
    { id: "maignan", name: "Mike Maignan", team: "fra", position: "POR" },
    { id: "bounou", name: "Yassine Bounou", team: "mar", position: "POR" },
    { id: "dibu", name: "Sergio Rochet", team: "uru", position: "POR" },
    { id: "gvardiol", name: "Joško Gvardiol", team: "cro", position: "DEF" },
    { id: "saliba", name: "William Saliba", team: "fra", position: "DEF" },
    { id: "hakimi", name: "Achraf Hakimi", team: "mar", position: "DEF" },
    { id: "dias", name: "Rúben Dias", team: "por", position: "DEF" },
    { id: "romero", name: "Cristian Romero", team: "arg", position: "DEF" },
    { id: "van-dijk", name: "Virgil van Dijk", team: "ned", position: "DEF" },
    { id: "trent", name: "Trent Alexander-Arnold", team: "eng", position: "DEF" },
    { id: "theo", name: "Theo Hernández", team: "fra", position: "DEF" },
    { id: "davies", name: "Alphonso Davies", team: "can", position: "DEF" },
    { id: "araujo", name: "Ronald Araújo", team: "uru", position: "DEF" },
    { id: "rodri", name: "Rodri", team: "esp", position: "MED" },
    { id: "bellingham", name: "Jude Bellingham", team: "eng", position: "MED" },
    { id: "valverde", name: "Federico Valverde", team: "uru", position: "MED" },
    { id: "pedri", name: "Pedri", team: "esp", position: "MED" },
    { id: "vitinha", name: "Vitinha", team: "por", position: "MED" },
    { id: "wirtz", name: "Florian Wirtz", team: "ger", position: "MED" },
    { id: "mac-allister", name: "Alexis Mac Allister", team: "arg", position: "MED" },
    { id: "hakha", name: "Hakan Çalhanoğlu", team: "tur", position: "MED" },
    { id: "kdb", name: "Kevin De Bruyne", team: "bel", position: "MED" },
    { id: "odegaard", name: "Martin Ødegaard", team: "nor", position: "MED" },
    { id: "kudus", name: "Mohammed Kudus", team: "gha", position: "MED" },
    { id: "enzo", name: "Enzo Fernández", team: "arg", position: "MED" },
    { id: "yamal", name: "Lamine Yamal", team: "esp", position: "DEL" },
    { id: "mbappe", name: "Kylian Mbappé", team: "fra", position: "DEL" },
    { id: "vinicius", name: "Vinícius Júnior", team: "bra", position: "DEL" },
    { id: "haaland", name: "Erling Haaland", team: "nor", position: "DEL" },
    { id: "kane", name: "Harry Kane", team: "eng", position: "DEL" },
    { id: "lautaro", name: "Lautaro Martínez", team: "arg", position: "DEL" },
    { id: "salah", name: "Mohamed Salah", team: "egy", position: "DEL" },
    { id: "leao", name: "Rafael Leão", team: "por", position: "DEL" },
    { id: "diaz", name: "Luis Díaz", team: "col", position: "DEL" },
    { id: "pulisic", name: "Christian Pulisic", team: "usa", position: "DEL" },
    { id: "kubo", name: "Takefusa Kubo", team: "jpn", position: "DEL" },
    { id: "mane", name: "Sadio Mané", team: "sen", position: "DEL" },
  ],
  pointsRules: [
    { label: "Marcador exacto", value: "Goles del partido" },
    { label: "Gol", value: "+2" },
    { label: "Penalti marcado", value: "+1" },
    { label: "MVP del partido", value: "+3" },
    { label: "Penalti parado", value: "+2" },
    { label: "Penalti fallado", value: "-1" },
    { label: "Tarjeta roja", value: "-2" },
    { label: "Acierto de clasificación", value: "+1" },
    { label: "Ganador del Mundial", value: "+5" },
    { label: "MVP o máximo goleador", value: "+5" },
  ],
  publicPlayers: [
    { id: "marta", name: "Marta R.", initials: "MR", points: 0, complete: 100, champion: "esp" },
    { id: "diego", name: "Diego L.", initials: "DL", points: 0, complete: 92, champion: "arg" },
    { id: "ines", name: "Inés P.", initials: "IP", points: 0, complete: 84, champion: "fra" },
    { id: "alex", name: "Álex M.", initials: "AM", points: 0, complete: 76, champion: "bra" },
  ],
};
